mysql:
  enabled: true
  image:
    repository: mysql
    tag: "8.4"
  database: appdb
  user: appuser
  pvc:
    name: mysql-pvc
    size: 8Gi
  service:
    type: NodePort
    port: 3306
    nodePort: 30306